debug = true
dev = true
host = "0.0.0.0"
port = 8888

[database]
name = "rulzurlibrary"
user = "rulzurlibrary"
host = "172.22.0.2"
port = 5432

[i18n]
default = "en-US"

[smtp]
user = "contact@rulz.xyz"
host = "ssl0.ovh.net"
port = 587
